### PR TITLE
Add vercel.json files to storefront and app-checkout packages

### PR DESCRIPTION
**Pull request by lkostrowski**
This points Vercel to explicitly set Next as framework in deployment context

# Why this is needed

[Deploy button api](https://vercel.com/docs/deploy-button) can't specify framework nor output directory settings. In monorepo, when react-storefront is being spawned, Next creates deployment with framework "Other" which is probably a bug.

It was reported to Vercel, but this local fix is transparent and fixes the problems

It will also be needed to close https://github.com/saleor/react-storefront/issues/466

### CODE REVIEW

**Review by krzysztofwolski — DISMISSED** [review]

**Review by mmiszy — COMMENTED** [review]
Looks good but I think you're missing empty lines at the end of both files?

**Comment by mmiszy** [comment]
Question: where was it reported to Vercel? Do you have a link to the issue so we can track it?

**Comment by lkostrowski** [comment]
@mmiszy 

Added empty lines - but I suggest to add this to eslint/prettier 

Regarding Vercel issue - I reported it from contact form yesterday, ticket is assigned to my account, will let you know what will be there answer...

...but when I think about it, vercel.json *should* be there even if this works. For tooling (CLI etc) the less "details" the better, so if application can store its config in the repository, that's perfect. We can narrow down integration to as small interface as possible

**Comment by mmiszy** [comment]
All files are prettified on commit – you must've skipped the pre-commit git hook @lkostrowski
I just tested this now on another branch and `vercel.json` files were automatically prettified for me when I committed.

**Comment by lkostrowski** [comment]
@mmiszy right, I probably changed it without installing deps, hence no husky too.

Also, I received answer from Vercel, they suggested to use vercel.json, so I assume we are doing right.

**Comment by lkostrowski** [comment]
@saleor/storefront-checkout I added also build and install overwrites to apps. Thanks to that, tooling that deploy storefront and checkout can ignore implementation details and integration should be less flaky

**Pull request merged**
