### PR TITLE
Handle products without the images at cart and checkout 

### PR DESCRIPTION
**Pull request by bandieramonte**
This PR aims to fix issue [203](https://github.com/saleor/react-storefront/issues/203), so that items without media images can now be added to the cart.

### CODE REVIEW

**Comment by matteius** [comment]
Not sure why the difference, but I am able to add products with out images to the cart.  For example:  https://mattscoinage.com/default-channel/en-US/products/test-stripe

**Comment by bandieramonte** [comment]
> Not sure why the difference, but I am able to add products with out images to the cart. For example: https://mattscoinage.com/default-channel/en-US/products/test-stripe

Interesting. In any case, I think this new code adds a safety layer for cases without images - it doesn't hurt.

**Review by krzysztofwolski — APPROVED** [review]
LGTM 👍

**Comment by krzysztofwolski** [comment]
Tested locally, and indeed it solves the issue with the products without the images :) 
Thanks for your contribution!

**Pull request merged**
