### PR TITLE
Dev Command updated to work for Windows OS

### PR DESCRIPTION
**Pull request by parasmanikc**
I got an error while running the "dev" command on my windows machine. Making this simple change in "package.json" fixes the issue

### CODE REVIEW

**Comment by zaiste** [comment]
@parasmanikc thanks, I've adjusted it directly in `package.json` in #92

**Comment by parasmanikc** [comment]
Great! Glad I could help, I would love to contribute more to this project.

@zaiste, I see in the projects tab, that you guys are also planning to integrate Stripe in this application. Is someone already working on that? If not I would love to make that contribution, as I have prior experience integrating Stripe in a NextJS App.

I wasn't able to find your email in your profile or on your website, so I decided to ask you here.

**Comment by zaiste** [comment]
@parasmanikc thanks for pointing it out.

We'd be more than happy if you'd like to help us out with the Stripe integration. The initial setup is already there. Let's decide together about the scope of this feature and split the work in the most optimal way for you and us.

**Comment by parasmanikc** [comment]
Great! Where should we discuss this? Do you have a slack group? You can add me on this email: parasmanikc@gmail.com

**Comment by zaiste** [comment]
@parasmanikc let's use [Discussion](https://github.com/saleor/react-storefront/discussions) for this. We are also starting a [Discord channel](https://discord.gg/t5UAQZDB7c) to establish a more conversational channel with the community.

**Pull request closed without merging**
